name: CI
on: [push, workflow_dispatch]

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            vcpkgCommitId: '4cb4a5c5ddcb9de0c83c85837ee6974c8333f032'
            preset: 'windows'
          - os: ubuntu-22.04
            vcpkgCommitId: '4cb4a5c5ddcb9de0c83c85837ee6974c8333f032'
            preset: 'unix'
          - os: macos-12
            vcpkgCommitId: '4cb4a5c5ddcb9de0c83c85837ee6974c8333f032'
            preset: 'unix'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set C++/C compiler on macOS
        shell: bash
        run: echo "CC=gcc-11" >> $GITHUB_ENV; echo "CXX=g++-11" >> $GITHUB_ENV; cat "$GITHUB_ENV"
        if: runner.os == 'macOS'

      - uses: friendlyanon/setup-vcpkg@v1
        with:
          committish: ${{ matrix.vcpkgCommitId }}

      - name: GCC version on Linux
        shell: bash
        run: g++ --version
        if: runner.os == 'Linux'

      - name: Run CMake with manifest mode vcpkg
        shell: bash
        run: cmake --preset=${{ matrix.preset }} -B build -DCalculator_Test=1 -DCalculator_Benchmark=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1

      - name: Compile binaries
        shell: bash
        run: cmake --build build

      - name: Run tests
        shell: bash
        run: ctest --test-dir build/Calculator_Test

      - name: Run benchmark
        shell: bash
        run: ./build/Calculator_Benchmark/Calculator_Benchmark
        if: runner.os == 'Linux' || runner.os == 'macOS'
