name: CI
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: 49 13 * * 2 # 13:49 every Tuesday

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            preset: 'windows'
          - os: ubuntu-latest
            preset: 'unix'
          - os: macos-latest
            preset: 'unix'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set C++/C compiler on macOS
        shell: bash
        run: echo "CC=gcc-11" >> "$GITHUB_ENV"; echo "CXX=g++-11" >> "$GITHUB_ENV"
        if: runner.os == 'macOS'

      - name: Set C++ VCPKG_ROOT
        shell: bash
        run: echo VCPKG_ROOT="$VCPKG_INSTALLATION_ROOT" >> "$GITHUB_ENV"; cat "$GITHUB_ENV"

      - name: Run CMake DEBUG
        shell: bash
        run: cmake --preset=${{ matrix.preset }} -B build_debug -DCalculator_Test=1 -DCalculator_Benchmark=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=1 -DCODE_COVERAGE=1

      - name: Compile binaries DEBUG
        shell: bash
        run: cmake --build build_debug

      - name: Run tests DEBUG
        shell: bash
        run: ctest --rerun-failed --output-on-failure --test-dir build_debug/Calculator_Test

      - name: Run code coverage
        shell: bash
        run: |
          sudo apt-get install lcov
          cd build_debug
          lcov -c -d . -b ../src --no-external -o lcov.info
          ls -ltr
        if: runner.os == 'Linux'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: build_debug
          files: lcov.info
        if: runner.os == 'Linux'

      - name: Run CMake RELEASE
        shell: bash
        run: cmake --preset=${{ matrix.preset }} -B build_release -DCalculator_Test=1 -DCalculator_Benchmark=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1

      - name: Compile binaries RELEASE
        shell: bash
        run: cmake --build build_release

      - name: Run tests RELEASE
        shell: bash
        run: ctest --rerun-failed --output-on-failure --test-dir build_release/Calculator_Test

      - name: Run benchmark RELEASE
        shell: bash
        run: ./build_release/Calculator_Benchmark/Calculator_Benchmark
        if: runner.os == 'Linux' || runner.os == 'macOS'
